### PR TITLE
Add go.mod/go.sum

### PR DESCRIPTION
**Pull request by sheenobu**
This could probably be separated out into two separate diffs: 1. go.mod/go.sum and 2. makefile updates. but current master and 0.7.0 is broken with go modules due to go-bindata go get failing (since there is no GOPATH). Feel free to edit/use as needed.

This fixes build issues with:

 * go-bindata, which attempted a go get ...
 * pinning ikeikeikeike/go-sitemap-generator to 1.0.1 instead of master
 * replace all go-get with go build -o tmpbin/

### CODE REVIEW

**Comment by thebaer** [comment]
@sheenobu Thanks for submitting this! By the way, your go-webfinger library was a big help for this project :slightly_smiling_face: 

If you don't mind splitting this into two PRs and making the Travis config change @SamWhited mentioned, that'll help a lot. Lastly, just need a quick signature on the [CLA](https://phabricator.write.as/L1) and then I'll get everything merged.

**Comment by sheenobu** [comment]
No worries! Should we bump travis conf to 1.11?

**Comment by thebaer** [comment]
Yep, that'll work!

**Comment by SamWhited** [comment]
Gentle ping; @sheenobu if you're not available to wrap this up, I'd be happy to rebase and get everything working. Let me know.

**Comment by SamWhited** [comment]
@sheenobu I was actually forgetting, this repo requires a CLA so I probably can't make makefile changes and what not because @thebaer considers those copyrightable code. I could update the go.mod file, which a tool is doing, but I guess I can't finish this off. Sorry.

**Comment by thebaer** [comment]
We now support Go modules, and I've used the Makefile as a starting place for a new `make ci` command that ensures Travis successfully builds. Thanks for the initial contribution and input, @sheenobu and @SamWhited!

**Pull request closed without merging**
