### PR TITLE
Shorter config process

### PR DESCRIPTION
**Pull request by qwazix**
This resolves T657: shorter-config-process by adding a --sections parameter that takes a space separated string of sections (app, db and server are the current valid ones).

### CODE REVIEW

**Comment by qwazix** [comment]
Btw, currently the program just ignores `--sections` if `--config` is not present. Do we want to throw an error?

**Comment by robjloranger** [comment]
That might be a good idea, error with the usage output.

**Comment by qwazix** [comment]
Ok will do.

**Comment by qwazix** [comment]
Now that I look at it...

As the code is now the whole flag parsing process is to match the first flag found and then ignore anything else, so it seems a bit out of place to throw an error in this particular combination (or lack thereof).

It's inconsistent to not throw any error at `writefreely --config --gen-keys` and do so at `writefreely --gen-keys --sections app` even though both exhibit the same behavior: they ignore the second flag.

**Comment by joyeusenoelle** [comment]
One approach might be to use `flag.Visit` to count the number of supplied flags; if it's >1 and the flags aren't `--config` and `--sections`, print an error ("One at a time, please") and then continue with the first flag as normal.

**Comment by qwazix** [comment]
I like this, since it will not fail silently in either case, without having to rework the whole thing. Let me take a stab at it.

**Comment by thebaer** [comment]
For some reason my earlier response didn't send, but I'd say yeah, it should fail silently as it does with other flags. The command-line side of WF is used infrequently enough that I'd say it's not worth getting too far in the weeds with it.

**Comment by qwazix** [comment]
Ok then, feel free to merge the PR as is.

**Comment by thebaer** [comment]
Went ahead and fixed these up. Thanks @qwazix! Merging now.

**Comment by qwazix** [comment]
Thanks, I missed that `go fmt`, though I admit I did read about it in the style guide :-/ Will make sure to run it next time.

**Comment by thebaer** [comment]
No worries!

**Pull request merged**
