### PR TITLE
Add touch icons

### PR DESCRIPTION
**Pull request by mrvdb**
These were missing.

Fix for #77
---

- [X ] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by thebaer** [comment]
Hey, good catch. We should use the WriteFreely logo (here for a [light background](https://writefreely.org/img/logo.svg) / [dark background](https://writefreely.org/img/logo-light.svg)) instead of the Write.as one.

Which one would you rather see? The logo on a light background, or on a dark one like the current Write.as logo?

**Comment by mrvdb** [comment]
I have no preference for a logo. I am unable to view the results as well, as I understand this is like a 'ios specific favicon' ? (i have no ios device)

**Comment by thebaer** [comment]
Ok, no problem. Yeah, this is only for iOS. I'll put together a new icon -- I should have a device somewhere I can test it out on.

**Comment by thebaer** [comment]
Alright, got the WriteFreely "w" in there. Thanks again for reporting this! Merging now.

**Comment by mrvdb** [comment]
Nice, thanks!

**Pull request merged**
