### PR TITLE
Dockerfile/docker-compose fixes

### PR DESCRIPTION
**Pull request by conor-f**
I recently tried to install writefreely using my docker-compose setup that I use for managing all self hosted services I'm running. It took a lot of work to get the docker-compose setup working for writefreely but this PR should make things significantly easier.

This is the workflow of this PR to install writefreely with docker-compose:

 - Take the `docker-compose.yml` that is modified in this PR, and put it in a directory.
 - Run:
```bash
touch config.ini
sudo chown root:root config.ini
sudo chmod 777 config.ini
```
	- Note that this is definitely not the right thing to do and permissions could certainly be tighter. If anyone has suggestions for me I'm more than willing to update this PR.
 - Then this sequence of commands:
```bash
sudo docker-compose up -d writefreely-db
sudo docker-compose run writefreely-web --config
sudo docker-compose run writefreely-web --gen-keys
vim config.ini <-- Only needed if you want to make other modifications
sudo docker-compose up -d writefreely-web
```

I know this is kind of messy still but this is working now so let me know any changes you'd like to see to get this merged. This should (mostly) solve #139 #323 and #357 

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by conor-f** [comment]
Any review on this? Happy to modify it as necessary

**Comment by thebaer** [comment]
Thanks for submitting this, @conor-f! It would be great to get these Docker issues fixed.

I won't be able to help much since this isn't my area of expertise, but maybe @shleeable or @kaiyou could review?

**Comment by finn-ball** [comment]
I just ran into the same issue. Changes look good to me.

**Comment by finn-ball** [comment]
Though I would make one suggestion, wouldn't it be easier to have a simple sqlite example instead of spinning up a mariadb image too?

**Comment by thebaer** [comment]
Thanks for taking a look, @finn-ball!

Just to be sure @conor-f, which issues in particular should be completely **closed** when we merge this?

**Comment by conor-f** [comment]
I would close the two issues and one PR I linked in the original comment.

There are improvements that could be made to this, but this PR will allow people to just pull the `docker-compose.yml` and get a working instance with significantly less hardship.

**Comment by thebaer** [comment]
Perfect, that'll work! Merging this now.

**Comment by zem** [comment]
@conor-f: please update the pr to do a  

```
sudo chmod 644 config.ini 
```
It should work with 644, that should be enough for the writefreely process to access.

**Pull request merged**
