### PR TITLE
lightly style tables in posts

### PR DESCRIPTION
**Pull request by robjloranger**
styling added:
- thin inner borders
- table body rows alternate light background
- table header text centered
- cellspacing reset and replaced with padding to avoid gaps in borders

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by thebaer** [comment]
This looks nice, but I think our default style should be as simple as possible, so it's as easy as possible to override with custom CSS. Then we can make this available as a fancier option.

Here, I think we should just make the table `width: 100%` and add some light borders.

**Comment by robjloranger** [comment]
How does this look? Or were you thinking outter borders as well? (ignore the top/left lines, screencap noise)

2020-02-11-085744_707x247_scrot

**Comment by thebaer** [comment]
Looks good, but is the CSS simple / easily to override?

**Comment by robjloranger** [comment]
2020-02-11-094647_675x216_scrot

I reworked it a bit to make it simpler to override. To change the style would require something like:

```css
article table {
  border-color: new-color;
}

article table th {
  font-size: 3em;
}
```

We could change to using a class but it would be similar to override like:

```css
table.post {
  border-color: new-color;
}

table.post th {
  font-size: 3em;
}
```

**Comment by thebaer** [comment]
Cool, I think that looks great :+1:

**Comment by cjeller1592** [comment]
Tables look good on my end! Both Chrome (80.0.3987) and Firefox (73.0.1) show the same table styling.

**Comment by thebaer** [comment]
Thanks @robjloranger and @cjeller1592! Looks good, merging now.

**Pull request merged**
