### PR TITLE
Admin dashboard redesign

### PR DESCRIPTION
**Pull request by thebaer**
Reworking the admin dashboard to be more organized, straightforward, and to optionally hide unnecessary information for non-technical admins in hosted environments like [Write.as for Teams](https://write.as/for/teams).

## Less-technical dashboard

This will close [T694](https://writefreely.org/tasks/694).

This hides the app Monitor tab on the dashboard if instance admin sets the following config value: `forest = true` (**note: experimental**).

This makes the App Configuration page more user-friendly by changing the user-facing language and adding descriptions to each item.

### New Admin Settings page

screencapture-localhost-7879-admin-settings-2020-02-25-14_26_58

### New Dashboard

screencapture-localhost-7879-admin-2020-02-25-14_27_21

### New Users page

Screenshot from 2020-02-25 14-43-31

### Update page

screencapture-localhost-7879-admin-updates-2020-02-25-14_42_49

Enabled with: `update_checks = true` (**note: experimental**).

## Automated "new version" checks

It also contains improvements to the automated update check system, both user-facing and on the backend (work started on #175 and [T572](https://writefreely.org/tasks/572)):

* Indicates a new update is available in the admin navigation bar
* Shows "last check" time in local timezone, like blog posts do
* Mentions update check error to admin when one occurs
* Mentions that update checks are disabled, when true and an admin navigates to the `/admin/updates` page
* Adds logging around update checks

### CODE REVIEW

**Comment by thebaer** [comment]
I think this is a pretty good stopping place for this pull request. Would love to hear any feedback on these changes!

**Comment by dariusk** [comment]
This looks great!

**Comment by thebaer** [comment]
Thanks @dariusk! Really glad you like it.

@cjeller1592 some documentation to add, so we can link from the admin Settings page:

* Choosing a name for your site
* Choosing a "Landing Page" value
* Choosing a "max blogs per user" value (unlimited, only one, or limited)
* Controlling registration (open, closed, invite-only for admins, invite-only for users)
* What it means to run a private instance vs. public instance

**Comment by thebaer** [comment]
@cjeller1592 I moved those documentation topics to [T728](https://writefreely.org/tasks/728). Will get this merged and then we can update the app in another PR once all of that is live.

**Pull request merged**
