### PR TITLE
Fix following from Mastodon with Authorized Fetch enabled

### PR DESCRIPTION
**Pull request by thebaer**
This fixes federation with Mastodon instances that have Authorized Fetch turned on by signing the GET request to fetch the actor when a blog is first followed.

Closes [T820](https://writefreely.org/tasks/820)

---

- ☑ I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by thebaer** [comment]
There were a few missing pieces, but this is ready for review now :+1:

**Comment by amwelles** [comment]
I just attempted to follow this blog: https://write.as/skepticaldruid from https://traingletoot.party, and I got the same result as before: it requests to follow, but the follow never actually goes through.

I am not sure if Authorized Fetch is turned on, but I am on Mastodon v3.3.0, and it’s all managed through https://masto.host. I’ve been looking forward to this fix, so let me know if I can help with any additional troubleshooting!

**Comment by thebaer** [comment]
Thanks for offering to help, @amwelles! Yeah, I think I'm seeing the same issue with following Write.as blogs from our Mastodon instance, https://writing.exchange (also managed through Masto.host). However, everything seems to work on our other (more seldom-used) Mastodon instance, https://m.abunchtell.com. Very strange.

 I'm going to do a little more digging, and will let you know if I could use help on anything!

**Comment by aaribaud** [comment]
FWIW, same issue from mastodon.art. Can help test too.

**Comment by thebaer** [comment]
Seem to have narrowed it down after [noticing this issue](https://writing.exchange/@matt/105867353568682337). Can you try these steps, to see if it fixes things?

1. On Mastodon, look up your Write.as (WriteFreely) blog and click "Cancel follow request"
2. On the WriteFreely blog you're unable to follow, publish a new post that mentions your Mastodon account, [like this](https://write.as/fediversefix/this-is-for-you-atmatt2atfosstodon-org-hopefully-it-fixes-your-issue).
3. On Mastodon, look up your blog again and press "Follow"
4. Wait a few seconds, refresh the page, and make sure the button now says "Unfollow" instead of "Cancel follow request" -- that means it worked.

**Comment by aaribaud** [comment]
Step 4: the switch to "Unfollow" was immediate and I did not even have to refresh.

However, while I was notified of the post from step 2 (makes sense as I was mentioned), further posts sent after step 4 did not cause any notification, or appear on my write.as profile as seen from my Mastodon account.

Enabling or disabling notifications (right next to the Unfollow button) changes nothing.

**Comment by thebaer** [comment]
Right, Mastodon switches it to "Unfollow" immediately no matter what, so you need to refresh the page to make sure it worked. When you refresh, does it still say "Unfollow"?

**Comment by aaribaud** [comment]
Nope -- Cancel follow request

**Comment by amwelles** [comment]
@thebaer I did get the mention notification, but the follow request did not go through afterward. Looks like @aaribaud is in the same boat. :)

**Comment by marcoXbresciani** [comment]
> Nope -- Cancel follow request
> 
> This seems to contradict the hypothesis that if an instance receives a connection _from_ write.as then it will unblock connections _to_ write.as; I can confirm that on step 2, my mastodon.art account was indeed notified that it had been mentioned in a write.as blog post.

Same behaviour of @aaribaud even for me: @AAMfP@fosstodon.org and https://write.as/marco-bresciani/

**Comment by thebaer** [comment]
@amwelles @aaribaud @marcoXbresciani, can you please try following your account again? I think I got to the bottom of this issue, which seems to only be related to our hosting environment on Write.as. I've since patched the issue, and am able to follow your accounts now.

**Comment by aaribaud** [comment]
Hey, seems it works! I unfollowed the write.as account, deleted previous blogs on write.as, published a new blog post mentioning my Mastodon.art account, followed my write.as account from my Mastodon.art account, refreshed... And this time I don't get a "Cancel follow request", I get a proper "Unfollow".

**Comment by marcoXbresciani** [comment]
Yessss it works, on my machine! 😁
________________________________

**Comment by amwelles** [comment]
Confirmed working for me as well! Thanks for all your work. 😊

**Comment by thebaer** [comment]
Great to hear! Thanks for testing this, everyone. Will get this merged.

**Pull request merged**
