### PR TITLE
Update writefreely-web image in docker-compose.yml

### PR DESCRIPTION
**Pull request by cjeller1592**
Updated with the official writeas/writefreely image on Docker Hub. This prevents the error in #416 from happening.

More than happy to take comments, edits, and other considerations.

---

- [X ] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Review by conor-f — APPROVED** [review]
Happy to approve this change but the [official image](https://hub.docker.com/r/writeas/writefreely) is 9 months old. How can that get updated?

**Comment by cjeller1592** [comment]
> Happy to approve this change but the [official image](https://hub.docker.com/r/writeas/writefreely) is 9 months old. How can that get updated?

I talked to @thebaer and he said he'll update the image. As soon as we get confirmation that it's updated then we'll merge the PR.

**Comment by conor-f** [comment]
Excellent, thanks @cjeller1592!

**Review by thebaer — APPROVED** [review]
Looks good, if this works for everyone! We should have a v0.13 release out soon, and we'll include this update along with a new Docker image then.

**Pull request merged**
