### PR TITLE
Update script

### PR DESCRIPTION
**Pull request by robjloranger**
add a basic update script for admins to check for and upgrade to the latest version of writefreely

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by thebaer** [comment]
Thanks @robjloranger! I just made a few minor tweaks to the wording and error handling. Also, I noticed the "current version" output gets messed up when using a custom build, where the version might be something like `0.9.1-50-gac7d727`

I don't think it's crucial to fix this right now for our purposes. But if it's quick to do, we should. What do you think, easy fix?

**Comment by robjloranger** [comment]
> Thanks @robjloranger! I just made a few minor tweaks to the wording and error handling. Also, I noticed the "current version" output gets messed up when using a custom build, where the version might be something like `0.9.1-50-gac7d727`
> 
> I don't think it's crucial to fix this right now for our purposes. But if it's quick to do, we should. What do you think, easy fix?

That should be an easy fix.

**Comment by robjloranger** [comment]
weird it still looks wrong, the spacing in the header

**Comment by robjloranger** [comment]
it looks fine in real life though
Screenshot from 2019-06-14 17-31-31

**Comment by thebaer** [comment]
Awesome, thanks! Spacing looks good :)

**Pull request merged**
