### PR TITLE
Mathjax in binaries

### PR DESCRIPTION
**Pull request by robjloranger**
removes the submodule for mathjax and instead includes a copy of the script

ref #176, will need a tag and new release to close

---

- [x] I have signed the [CLA](https://phabricator.write.as/L1)

### CODE REVIEW

**Comment by thebaer** [comment]
I think we also need the fonts and images from the library, right?

**Comment by robjloranger** [comment]
I'm not certain, the docs just say to link the one script.

I did notice that the body is not being parsed properly though so I will need to see what's going on here.

**Comment by robjloranger** [comment]
this uses the svg version which does not require any external fonts
Screenshot from 2019-09-11 14-17-28

**Comment by thebaer** [comment]
I'm not sure how to verify this since I'm not really a user of this feature. If anyone in the community can try it out and weigh in on whether or not it works, please do!

**Comment by robjloranger** [comment]
Hey @thebaer, to verify this is working you can try somewhere like http://atomurl.net/math/ and use a sample from the selection. This will give you the markup and a preview of it rendered to compare to.

**Comment by thebaer** [comment]
Worked for me! Merging now.

**Pull request merged**
